### ISSUE TITLE
Instalar usando git clone causa conflito com o git

### ISSUE THREAD

**Issue by graciano** [bmonteirog/laravel-5.1-pt-br-localization#5]
Ao instalar usando `git clone ...` uma pasta `.git/` é criada no meu projeto, que está usando git. Eu precisei removê-la para prevenir problemas.

Enfim, recomendo que coloque um aviso na instalação, por exemplo

``` shell
$ cd resources/lang/
$ git clone git@github.com:bmonteirog/laravel-5.1-pt-br-localization.git ./pt-br
$ rm -r pt-br/.git/ # previne possíveis conflitos com seu repositório git
```

**Comment by bmonteirog** [comment]
https://github.com/bmonteirog/laravel-5.1-pt-br-localization/commit/3c133f0155949a60a29b96d44807a6771b8049b4

Obrigado! :+1:
